task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('login/',views.loginView,name='login'),
    path('signup/',views.signup,name='signup'),
    path('about/',views.aboutView,name='about'),
    path('user_login/',views.userLogin,name='user_login'),
    path('add_todo/',views.addTodo,name='add_todo'),
    path('logout/',views.userLogout,name='logout_user'),
    path('update_task/<int:pk>/update/',views.updateTodo,name='update_task'),
    path('delete_task/<int:pk>/remove/',views.deleteTodo,name='delete_task'),
    path('complete_task/<int:pk>/completed/',views.taskComplete,name='complete_task'),
    path('completed_tasks/',views.completedTasks,name='accomplished_tasks_list'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from task import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.todoView,name='home'),
    path('task/',include('task.urls')),
]

task/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Task(models.Model):
    
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)
    created_Date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = 'user'

task/forms.py
from django import forms
from django.contrib.auth import models
from django.contrib.auth.models import User
from .models import Task


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username','email','password')


class TaskForm(forms.ModelForm):
    title = forms.CharField(widget= forms.TextInput(attrs={'placeholder':'Add new task...'}),label='')
    class Meta:
        model = Task
        fields = ('title',)

task/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import UserForm, TaskForm
from .models import Task
from django.urls import reverse_lazy

# Create your views here.

# Home Page
def todoView(request):

    user = request.user
    if user.is_authenticated:
        task_form = TaskForm()
        todos = Task.objects.filter(user=user).order_by('created_Date')
        return render(request,'task/task_list.html',{'task_form':task_form, 'todos':todos})
    else:
        return render(request,'task/task_list.html')


# Signup page
def signup(request):

    #registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            return HttpResponseRedirect(reverse('task:login'))
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request,'task/signup.html',{'user_form':user_form})


# Login page
def userLogin(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                auth_login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print('Someone tried to login')
            print("Username: {} and Password {}".format(username,password))
            return HttpResponse("Invalid Credentials")

    else:
        return render(request,'task/login.html')


@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse(todoView))


# About page
def aboutView(request):
    return render(request,'task/about.html')


# login
def loginView(request):
    return render(request,'task/login.html')
    

@login_required
def addTodo(request):
    user = request.user
    if user.is_authenticated:
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            todo = task_form.save(commit=False)
            todo.user = user
            todo.save()
            return redirect('home')
        else: 
            return render(request ,'task_list.html', context={'task_form' : task_form})
    else:
        pass


@login_required
def deleteTodo(request,pk):
    task = Task.objects.get(pk=pk)
    task.delete()
    return redirect('home')


@login_required
def updateTodo(request,pk):

    task = Task.objects.get(pk=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('home')

    return render(request,'task/update_task.html',{'form':form})


@login_required
def taskComplete(request,pk):

    task = Task.objects.get(pk=pk)
    task.completed = True
    task.save()

    return redirect('home')


@login_required
def completedTasks(request):

    user = request.user
    todos = Task.objects.filter(completed=True,user=user)

    return render(request,'task/completed_tasks_list.html',{'todos':todos})

task/templates/task/about.html
{% extends "task/base.html" %}

{% block base %}

    <div class="abt">
        <h1 id="abt1">This app is created by Ishwar Shelke.</h1>
        <h1 id="abt2">TechStack - HTML, CSS, Bootstrap, Django.</h1>
    </div>

{% endblock %}

task/templates/task/base.html
<!DOCTYPE html>
{% load static %}
<head>
<html lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo App</title>

    <!--CSS file-->
    <link rel="stylesheet" href="{% static '/css/master.css' %}">

    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
</head>
<body>
    
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light custom-color">
        <div class="container-fluid">

          <a class="navbar-brand" href="{% url 'home' %}">ToDo</a>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'task:about' %}">About</a>
              </li>
              {% if user.is_authenticated == False %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/admin/">Admin</a>
                </li> 
              {% endif %}
            </ul>
          </div>

          {% if user.is_authenticated %}        
            <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="{% url 'task:accomplished_tasks_list' %}">TasksAccomplished</a>
            </div>
            <div class="nav-right">
                <a href="{% url 'task:logout_user' %}"><button type="button" class="btn btn-info">Logout</button></a>
            </div>
          {% else %}
            <div class="nav-right">
                <a href="{% url 'task:login' %}"><button type="button" class="btn btn-info">Login</button></a>
                <a href="{% url 'task:signup' %}"><button type="button" class="btn btn-info">Signup</button></a>
            </div>
          {% endif %}

        </div>
    </nav>

    <div class="wrapper">
        {% block base %} {% endblock %}
        <div class="push"></div>
    </div>

    <!-- footer -->

    <footer class="footer custom-footer">
        <p style="text-align:center;">Copyright @IshwarShelke</p>
    </footer>


</body>
</html>

task/templates/task/completed_tasks_list.html
{% extends "task/base.html" %}

{% block base %}

    <h2 class="text-center mt-3" style="font-size:22px;">Tasks you have completed so far.</h2>
    <hr>

    {% if todos|length == 0 %}
        <p class="text-center" style="font-size: 20px;">You have not finished any task yet.</p>
    {% else %}
        <div class="slide-right" style="margin-left:555px">
            {% for todo in todos %}
                <h2 style="font-size:20px;">{{ todo }}</h2>
            {% endfor %}
        </div>
    {% endif %}

{% endblock %}

task/templates/task/login.html
{% extends "task/base.html" %}

{% block base %}

<div class="text-center bg-light mt-4 p-4">
    <h1>Please Login</h1>
    <div class="row">
    <form action="{% url 'task:user_login' %}" method="POST">
        {% csrf_token %}

        <label for="username">Username</label>
        
        <input type="text" name="username" placeholder="Enter Username">
        <br>
        <br>
        <label for="password">Password</label>

        <input type="password" name="password" placeholder="Enter Password">
        <br>
        <br>
        <input type="submit" value="Login" class="btn btn-outline-secondary">
    </form>
</div>
</div>

{% endblock %}

task/templates/task/signup.html
{% extends "task/base.html" %}

{% block base %}

<div class="text-center bg-light mt-4 p-4">
    <h1>Register here</h1>
    <form method="POST" class="form-floating">
        {% csrf_token %}
                {% for field in user_form %}
                    <div class="mt-3">
                        {{ field.label_tag }}{{ field }}  
                    </div>
                {% endfor %}
        <br>
        <input type="submit" value="Register" class="btn btn-outline-secondary">
    </form>
</div>

{% endblock %}

task/templates/task/task_list.html
{% extends "task/base.html" %}

{% block base %}

    {% if user.is_authenticated %}
        <div class="text-center p-5">
            <form action="{% url 'task:add_todo' %}" method="POST">
                {% csrf_token %}
                {{ task_form.as_p }}
                <hr>
                <input type="submit" value="Add" class="btn btn-info">
            </form>

                <!--Show all the tasks to be completed-->
                <table class="center">
                    <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    </tr>

                    <div class="item-row">
                    {% for todo in todos %}
                        {% if todo.completed == False %}
                            <tr>
                                <td><label><h2 style="font-size:23px;">{{ todo }}</h2></label></td>
                                <td><a href="{% url 'task:update_task' pk=todo.pk %}" class="btn btn-sm btn-warning">Update</a></td>                                
                                <td><a href="{% url 'task:delete_task' pk=todo.pk %}" class="btn btn-sm btn-danger">Delete</a></td>                                   
                                <td><a href="{% url 'task:complete_task' pk=todo.pk %}">&check;</a></td>
                            </tr>
                        {% endif %}        
                    {% endfor %}
                    
                    </div>
                </table>
            
        </div>

    {% else %}
        <div class="text-center mt-5">
            <h2>Welcome to the todo application!!!!</h2>
            <p>To see your todo list you must login first.</p>
        </div>
    {% endif %}

{% endblock %}

task/templates/task/update_task.html
{% extends "task/base.html" %}

{% block base %}

    <div class="text-center mt-4 p-4">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <hr>
            <input type="submit" value="Update" class="btn btn-warning">
        </form>
    </div>

{% endblock %}